name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npx jest      
        
      - name: Ver entorno
        run: 'echo "Entorno actual: ${{ secrets.NODE_ENV }}"'